# Generated by Django 3.1 on 2020-08-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgsRestApp', '0002_auto_20200807_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardinfo',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcardinfo',
            name='cvv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcardinfo',
            name='exp_date',
            field=models.CharField(max_length=100),
        ),
    ]
